
package ucoach.data.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GoogleTokensInterface", targetNamespace = "http://ws.data.ucoach/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GoogleTokensInterface {


    /**
     * 
     * @param accessToken
     * @param userId
     * @param refreshToken
     * @return
     *     returns ucoach.data.ws.GoogleTokens
     */
    @WebMethod
    @WebResult(name = "tokens", targetNamespace = "")
    @RequestWrapper(localName = "setTokens", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.ws.SetTokens")
    @ResponseWrapper(localName = "setTokensResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.ws.SetTokensResponse")
    @Action(input = "http://ws.data.ucoach/GoogleTokensInterface/setTokensRequest", output = "http://ws.data.ucoach/GoogleTokensInterface/setTokensResponse")
    public GoogleTokens setTokens(
        @WebParam(name = "userId", targetNamespace = "")
        int userId,
        @WebParam(name = "accessToken", targetNamespace = "")
        String accessToken,
        @WebParam(name = "refreshToken", targetNamespace = "")
        String refreshToken);

    /**
     * 
     * @param userId
     * @return
     *     returns ucoach.data.ws.GoogleTokens
     */
    @WebMethod
    @WebResult(name = "tokens", targetNamespace = "")
    @RequestWrapper(localName = "getTokens", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.ws.GetTokens")
    @ResponseWrapper(localName = "getTokensResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.ws.GetTokensResponse")
    @Action(input = "http://ws.data.ucoach/GoogleTokensInterface/getTokensRequest", output = "http://ws.data.ucoach/GoogleTokensInterface/getTokensResponse")
    public GoogleTokens getTokens(
        @WebParam(name = "userId", targetNamespace = "")
        int userId);

}
