
package ucoach.data.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HealthMeasureInterface", targetNamespace = "http://ws.data.ucoach/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HealthMeasureInterface {


    /**
     * 
     * @return
     *     returns java.util.List<ucoach.data.ws.HmType>
     */
    @WebMethod
    @WebResult(name = "HMType", targetNamespace = "")
    @RequestWrapper(localName = "getHMTypes", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.ws.GetHMTypes")
    @ResponseWrapper(localName = "getHMTypesResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.ws.GetHMTypesResponse")
    @Action(input = "http://ws.data.ucoach/HealthMeasureInterface/getHMTypesRequest", output = "http://ws.data.ucoach/HealthMeasureInterface/getHMTypesResponse")
    public List<HmType> getHMTypes();

}
