
package ucoach.data.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HealthMeasureService", targetNamespace = "http://ws.data.ucoach/", wsdlLocation = "http://192.168.137.82:6900/ws/healthmeasure?wsdl")
public class HealthMeasureService
    extends Service
{

    private final static URL HEALTHMEASURESERVICE_WSDL_LOCATION;
    private final static WebServiceException HEALTHMEASURESERVICE_EXCEPTION;
    private final static QName HEALTHMEASURESERVICE_QNAME = new QName("http://ws.data.ucoach/", "HealthMeasureService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.137.82:6900/ws/healthmeasure?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HEALTHMEASURESERVICE_WSDL_LOCATION = url;
        HEALTHMEASURESERVICE_EXCEPTION = e;
    }

    public HealthMeasureService() {
        super(__getWsdlLocation(), HEALTHMEASURESERVICE_QNAME);
    }

    public HealthMeasureService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HEALTHMEASURESERVICE_QNAME, features);
    }

    public HealthMeasureService(URL wsdlLocation) {
        super(wsdlLocation, HEALTHMEASURESERVICE_QNAME);
    }

    public HealthMeasureService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HEALTHMEASURESERVICE_QNAME, features);
    }

    public HealthMeasureService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HealthMeasureService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HealthMeasureInterface
     */
    @WebEndpoint(name = "HealthMeasureServicePort")
    public HealthMeasureInterface getHealthMeasureServicePort() {
        return super.getPort(new QName("http://ws.data.ucoach/", "HealthMeasureServicePort"), HealthMeasureInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HealthMeasureInterface
     */
    @WebEndpoint(name = "HealthMeasureServicePort")
    public HealthMeasureInterface getHealthMeasureServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.data.ucoach/", "HealthMeasureServicePort"), HealthMeasureInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HEALTHMEASURESERVICE_EXCEPTION!= null) {
            throw HEALTHMEASURESERVICE_EXCEPTION;
        }
        return HEALTHMEASURESERVICE_WSDL_LOCATION;
    }

}
