
package ucoach.data.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserInterface", targetNamespace = "http://ws.data.ucoach/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserInterface {


    /**
     * 
     * @param userId
     * @return
     *     returns ucoach.data.ws.User
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.ws.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.ws.GetUserResponse")
    @Action(input = "http://ws.data.ucoach/UserInterface/getUserRequest", output = "http://ws.data.ucoach/UserInterface/getUserResponse")
    public User getUser(
        @WebParam(name = "userId", targetNamespace = "")
        int userId);

    /**
     * 
     * @param email
     * @return
     *     returns ucoach.data.ws.User
     */
    @WebMethod
    @WebResult(name = "userByEmail", targetNamespace = "")
    @RequestWrapper(localName = "getUserByEmail", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.ws.GetUserByEmail")
    @ResponseWrapper(localName = "getUserByEmailResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.ws.GetUserByEmailResponse")
    @Action(input = "http://ws.data.ucoach/UserInterface/getUserByEmailRequest", output = "http://ws.data.ucoach/UserInterface/getUserByEmailResponse")
    public User getUserByEmail(
        @WebParam(name = "email", targetNamespace = "")
        String email);

    /**
     * 
     * @param user
     * @return
     *     returns ucoach.data.ws.User
     */
    @WebMethod
    @WebResult(name = "createdUser", targetNamespace = "")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.ws.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.ws.CreateUserResponse")
    @Action(input = "http://ws.data.ucoach/UserInterface/createUserRequest", output = "http://ws.data.ucoach/UserInterface/createUserResponse")
    public User createUser(
        @WebParam(name = "user", targetNamespace = "")
        User user);

    /**
     * 
     * @param user
     * @return
     *     returns ucoach.data.ws.User
     */
    @WebMethod
    @WebResult(name = "updateUser", targetNamespace = "")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.ws.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.ws.UpdateUserResponse")
    @Action(input = "http://ws.data.ucoach/UserInterface/updateUserRequest", output = "http://ws.data.ucoach/UserInterface/updateUserResponse")
    public User updateUser(
        @WebParam(name = "user", targetNamespace = "")
        User user);

    /**
     * 
     * @param userId
     */
    @WebMethod
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.ws.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.ws.DeleteUserResponse")
    @Action(input = "http://ws.data.ucoach/UserInterface/deleteUserRequest", output = "http://ws.data.ucoach/UserInterface/deleteUserResponse")
    public void deleteUser(
        @WebParam(name = "userId", targetNamespace = "")
        int userId);

}
