
package ucoach.data.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserInterface", targetNamespace = "http://ws.data.ucoach/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserInterface {


    /**
     * 
     * @param userId
     * @return
     *     returns ucoach.data.ws.User
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.ws.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.ws.GetUserResponse")
    @Action(input = "http://ws.data.ucoach/UserInterface/getUserRequest", output = "http://ws.data.ucoach/UserInterface/getUserResponse")
    public User getUser(
        @WebParam(name = "userId", targetNamespace = "")
        int userId);

}
